export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD';
export const UPDATE_SEARCH_LOCATION = 'UPDATE_SEARCH_LOCATION';
export const UPDATE_SEARCH_AGE = 'UPDATE_SEARCH_AGE';
export const UPDATE_SELECTED_USER = 'UPDATE_SELECTED_USER';
